### ISSUE TITLE
Wildcard plus parent as SAN

### ISSUE THREAD

**Issue by RivBoyce** [PKISharp/ACME-PS#80]
Hi folks, it's a common configuration to get a certificate that is a wildcard and to have the domain section as a Subject Alternate Name so that the cert covers all usage to one level.

I tried to integrate the sample code for multiple domains with the example script someone else provided. And I switched to DNS for the proofing as that's what I have available.

[ACME-PS_demo_code.txt](https://github.com/PKISharp/ACME-PS/files/4620113/ACME-PS_demo_code.txt)

**Comment by glatzert** [comment]
Hey there,
I see two things:

```
# this was commented out, but to explain what happens
$identifier = New-ACMEIdentifier $dnsIdentifiers
```
`$dnsIdentifiers` is an Array, you can use an array of strings in `New-ACMEOrder`, since it'll be converted automatically, but you can't to create the identifiers, correct IMO would be
```
$identifiers = $dnsIdentifiers | % { New-AcmeIdentifier $_ }
```

Something else:
```
$authZ = Get-ACMEAuthorization -State $state -Order $order # This is whereit fails
```
will (probably) return an array, so you need to foreach after that.
If the line itself fails, you should be able to see the full error, with the latest version (1.1.10) - please provide that. Or if it's not displayed directly the automatic `$error` should contain the problems.

```
$error[0]
# or
$error[0].Exception
```

**Comment by RivBoyce** [comment]
Heya, thanks for the quick reply. I tried it with and without so left both in for you to see... That piece didn't work, so replacing it with the section from the multi sample got me what looked closer but I suspect is just as far. You're right that it returned an array. I'll try this tomorrow. Thanks again!
