### ISSUE TITLE
You need to provide a certificate key or enable automatic generation.

### ISSUE THREAD

**Issue by jcnewman83** [PKISharp/ACME-PS#84]
I have come up against an issue where when I am trying to complete a certificate request, I am being presented with an error informing me that I need to provide a key even though I have provided the -GenerateCertificateKey flag to the Complete-ACMEOrder method.

I have included the full script I am using below, this does feel like something that has changed in the last few days because this script has been previously working for us for some time now.

Thank you in advance for any assistance you can offer. 

I am using version 1.2.2

`param (
	[string]$email,
	[string]$domain,
	[string]$iissitename,
    [string]$droppath
)

	
## Display vars
Write-Host "ASSIGNED PARAMETER VALUES:"
Write-Host "Contact email: $($email)"
Write-Host "Domain to register: $($domain)"
Write-Host "IIS Site Name: $($iissitename)"
Write-Host ""

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

## To prevent invalid code signing errors, change execution policy for this session
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

# ServiceName (valid names are LetsEncrypt and LetsEncrypt-Staging, use the latter one for testing your scripts).
$acmeServiceName = "LetsEncrypt";

# Your email addresses, where acme services will send informations.
$contactMailAddresses = @($email);

# This directory is used to store your account key and service directory urls as well as orders and related data
$acmeStateDir = "$($droppath)\AcmeState";

# This directory will be used to store the certificate in
$certExportDirectory = "$($droppath)\certificates\";

# This path will be used to export your certificate file.
$certExportPath = "$($certExportDirectory)\$iissitename.pfx";

# This path will be used to point to the default website folder
$iisPath = (Get-Website -Name $iissitename).physicalPath -replace "%SystemDrive%",$env:SystemDrive;

###############################################################################################
##Account
###############################################################################################
Write-Host "Initialising...";
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name 'ACME-PS' -AllowClobber -Confirm:$False -Force;

Import-Module 'ACME-PS';
Import-Module WebAdministration;

Write-Host "Create account";

if(Test-path $acmeStateDir -PathType Container){
    Remove-Item –path $acmeStateDir –recurse
}
# Create the state object - will be saved to disk
$account = New-ACMEState -Path $acmeStateDir;

# Load URLs from service directory
Get-ACMEServiceDirectory -State $acmeStateDir -ServiceName $acmeServiceName;

# Retrieve the first anti-replay nonce
New-ACMENonce -State $acmeStateDir;

# Create an account key and store it to the state
New-ACMEAccountKey -State $acmeStateDir;

# Register account key with acme service
New-ACMEAccount -State $acmeStateDir -EmailAddresses $contactMailAddresses -AcceptTOS;

###############################################################################################
##Order
###############################################################################################
Write-Host "Create order";
# This dns name will be used as identifier
$dnsIdentifiers = New-ACMEIdentifier $domain;

# Create a new order
$order = New-ACMEOrder -State $acmeStateDir -Identifiers $dnsIdentifiers;
###############################################################################################
##Verify order
###############################################################################################
Write-Host "Verifying order";
# Fetch the authorizations for that order
$authorizations = @(Get-ACMEAuthorization -State $acmeStateDir -Order $order);

foreach($authz in $authorizations) {
    # Select a challenge to fullfill
    $challenge = Get-ACMEChallenge -State $acmeStateDir -Authorization $authZ -Type "http-01";

    # Inspect the challenge data (uncomment, if you want to see the object)
    # Depending on the challenge-type this will include different properties
    # $challenge.Data;
    
    $chFilename = "$($iisPath)\$($challenge.Data.RelativeUrl)";
    $chDirectory = [System.IO.Path]::GetDirectoryName($chFilename);
    $VirtualPath = "$($iissitename)/.well-known/acme-challenge";
    
    # Ensure the challenge directory exists
    if(-not (Test-Path $chDirectory)) {
        New-Item -Path $chDirectory -ItemType Directory;
    }
    #add mime type
    if(!((Get-WebConfiguration //staticcontent -Location $VirtualPath).collection | ? {$_.fileextension -eq ".*"})){
        add-webconfigurationproperty //staticContent -name collection -Location $VirtualPath -value @{fileExtension=".*"; mimeType="text/plain"}
    }
    #add handler
    if(!(Get-WebHandler -Name "StaticFileForChallenge" -Location $VirtualPath)){
        New-WebHandler -Name "StaticFileForChallenge" -Path "*" -Verb "*" -Modules "StaticFileModule,DefaultDocumentModule,DirectoryListingModule" -Location $VirtualPath -ResourceType Either -RequiredAccess Read
    }

    Set-Content -Path $chFilename -Value $challenge.Data.Content -NoNewline;
    
    Write-Host "Challenge url http://$($challenge.Data.AbsoluteUrl)";

    # Signal the ACME server that the challenge is ready
    $challenge | Complete-ACMEChallenge -State $acmeStateDir;
}
###############################################################################################
##Get certificate
###############################################################################################
#retreived the updated order
$order = Find-ACMEOrder -State $acmeStateDir -Identifiers $dnsIdentifiers;

Write-Host "Waiting on order";
# Wait a little bit and update the order, until we see the status 'ready' or 'invalid'
try {
    while($order.Status -notin ("ready","invalid")) {
        Start-Sleep -Seconds 10;
        $order | Update-ACMEOrder -State $acmeStateDir -PassThru;
    }
} catch{
    throw "Error: Unable to determine order status";
}

#Throw error is order is invalid
if($order.Status -eq "invalid") {
    $order;
    throw "Your order has been marked as invalid - certificate cannot be issued.";
}
Write-Host "Completing certificate request";
# Complete the order - this will issue a certificate singing request
Complete-ACMEOrder -State $acmeStateDir -Order $order -GenerateCertificateKey;

# Now we wait until the ACME service provides the certificate url
while(-not $order.CertificateUrl) {
    Start-Sleep -Seconds 15;
    $order | Update-Order -State $acmeStateDir -PassThru;
}
Write-Host "Exporting certificate - $($certExportPath)";
#Ensure the certificate folder exists
 if(-not (Test-Path $certExportDirectory)) {
    New-Item -Path $certExportDirectory -ItemType Directory;
}

#remove any existing exported certificate
if(Test-Path $certExportPath) {
    Remove-Item -Path $certExportPath -Force
}

# As soon as the url shows up we can create the PFX
Export-ACMECertificate -State $acmeStateDir -Order $order -Path $certExportPath;

###############################################################################################
##IIS binding
###############################################################################################
Write-Host "IIS binding";

#Import Certificate
$certStorePath = "Cert:\LocalMachine\My";
$certStore = "My";
$pfx = Import-PfxCertificate -FilePath $certExportPath -CertStoreLocation $certStorePath;
$certThumbprint = $pfx.Thumbprint;

#Create Binding
if(!(Get-WebBinding -Name $iissitename -Port 443 -Protocol "https")){
    New-WebBinding -Name $iissitename -IPAddress "*" -Port 443 -Protocol "https" -HostHeader $domain -SslFlags 1 -ErrorAction Stop;
}

#Set Certificate
$binding = Get-WebBinding -Name $iissitename -Port 443 -Protocol "https";
if($binding){
    #Check for and remove any existing certificate
    if(!($binding.certificateHash -eq "")){
        $binding.RemoveSslCertificate();
    }
    #add the new certificate
    $binding.AddSslCertificate($certThumbprint, $certStore);
} else{
    throw "Error: SSL certificate assigment to $($iissitename) failed. This can be applied manually instead.";
}`

**Comment by glatzert** [comment]
Use Get-Module ACME-PS -ListAvailable and report the installed version numbers, please

Am 21.05.2020 12:31 schrieb jcnewman83 <notifications@github.com>:

I have come up against an issue where when I am trying to complete a certificate request, I am being presented with an error informing me that I need to provide a key even though I have provided the -GenerateCertificateKey flag to the Complete-ACMEOrder method.

I have included the full script I am using below, this does feel like something that has changed in the last few days because this script has been previously working for us for some time now.

Thank you in advance for any assistance you can offer.

`param (
[string]$email,
[string]$domain,
[string]$iissitename,
[string]$droppath
)

Display vars

Write-Host "ASSIGNED PARAMETER VALUES:"
Write-Host "Contact email: $($email)"
Write-Host "Domain to register: $($domain)"
Write-Host "IIS Site Name: $($iissitename)"
Write-Host ""

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

PARAMETERS
$email = "mailto:my.name@domain.co.uk<mailto:my.name@domain.co.uk>"
domain - This is the DNS of the Site. It should be accessable from the Internet.
iisSiteName - This is the Name of the Site as seen in the IIS Management Console.
EXAMPLE
.\PATHTOSCRIPT\GenerateSSLCert.ps1 -domain "test1234.uksouth.cloudapp.com" -iisSiteName "Default Web Site" - email "my.name@domain.co.uk<mailto:my.name@domain.co.uk>"
To prevent invalid code signing errors, change execution policy for this session

Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass

ServiceName (valid names are LetsEncrypt and LetsEncrypt-Staging, use the latter one for testing your scripts).

$acmeServiceName = "LetsEncrypt";

Your email addresses, where acme services will send informations.

$contactMailAddresses = @($email);

This directory is used to store your account key and service directory urls as well as orders and related data

$acmeStateDir = "$($droppath)\AcmeState";

This directory will be used to store the certificate in

$certExportDirectory = "$($droppath)\certificates";

This path will be used to export your certificate file.

$certExportPath = "$($certExportDirectory)$iissitename.pfx";

This path will be used to point to the default website folder

$iisPath = (Get-Website -Name $iissitename).physicalPath -replace "%SystemDrive%",$env:SystemDrive;

###############################################################################################
##Account
###############################################################################################
Write-Host "Initialising...";
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
Install-Module -Name 'ACME-PS' -AllowClobber -Confirm:$False -Force;

Import-Module 'ACME-PS';
Import-Module WebAdministration;

Write-Host "Create account";

if(Test-path $acmeStateDir -PathType Container){
Remove-Item –path $acmeStateDir –recurse
}

Create the state object - will be saved to disk

$account = New-ACMEState -Path $acmeStateDir;

Load URLs from service directory

Get-ACMEServiceDirectory -State $acmeStateDir -ServiceName $acmeServiceName;

Retrieve the first anti-replay nonce

New-ACMENonce -State $acmeStateDir;

Create an account key and store it to the state

New-ACMEAccountKey -State $acmeStateDir;

Register account key with acme service

New-ACMEAccount -State $acmeStateDir -EmailAddresses $contactMailAddresses -AcceptTOS;

###############################################################################################
##Order
###############################################################################################
Write-Host "Create order";

This dns name will be used as identifier

$dnsIdentifiers = New-ACMEIdentifier $domain;

Create a new order

$order = New-ACMEOrder -State $acmeStateDir -Identifiers $dnsIdentifiers;
###############################################################################################
##Verify order
###############################################################################################
Write-Host "Verifying order";

Fetch the authorizations for that order

$authorizations = @(Get-ACMEAuthorization -State $acmeStateDir -Order $order);

foreach($authz in $authorizations) {
# Select a challenge to fullfill
$challenge = Get-ACMEChallenge -State $acmeStateDir -Authorization $authZ -Type "http-01";

# Inspect the challenge data (uncomment, if you want to see the object)

# Depending on the challenge-type this will include different properties

# $challenge.Data;



$chFilename = "$($iisPath)\$($challenge.Data.RelativeUrl)";

$chDirectory = [System.IO.Path]::GetDirectoryName($chFilename);

$VirtualPath = "$($iissitename)/.well-known/acme-challenge";



# Ensure the challenge directory exists

if(-not (Test-Path $chDirectory)) {

    New-Item -Path $chDirectory -ItemType Directory;

}

#add mime type

if(!((Get-WebConfiguration //staticcontent -Location $VirtualPath).collection | ? {$_.fileextension -eq ".*"})){

    add-webconfigurationproperty //staticContent -name collection -Location $VirtualPath -value @{fileExtension=".*"; mimeType="text/plain"}

}

#add handler

if(!(Get-WebHandler -Name "StaticFileForChallenge" -Location $VirtualPath)){

    New-WebHandler -Name "StaticFileForChallenge" -Path "*" -Verb "*" -Modules "StaticFileModule,DefaultDocumentModule,DirectoryListingModule" -Location $VirtualPath -ResourceType Either -RequiredAccess Read

}



Set-Content -Path $chFilename -Value $challenge.Data.Content -NoNewline;



Write-Host "Challenge url http://$($challenge.Data.AbsoluteUrl)";



# Signal the ACME server that the challenge is ready

$challenge | Complete-ACMEChallenge -State $acmeStateDir;



}
###############################################################################################
##Get certificate
###############################################################################################
#retreived the updated order
$order = Find-ACMEOrder -State $acmeStateDir -Identifiers $dnsIdentifiers;

Write-Host "Waiting on order";

Wait a little bit and update the order, until we see the status 'ready' or 'invalid'

try {
while($order.Status -notin ("ready","invalid")) {
Start-Sleep -Seconds 10;
$order | Update-ACMEOrder -State $acmeStateDir -PassThru;
}
} catch{
throw "Error: Unable to determine order status";
}

#Throw error is order is invalid
if($order.Status -eq "invalid") {
$order;
throw "Your order has been marked as invalid - certificate cannot be issued.";
}
Write-Host "Completing certificate request";

Complete the order - this will issue a certificate singing request

Complete-ACMEOrder -State $acmeStateDir -Order $order -GenerateCertificateKey;

Now we wait until the ACME service provides the certificate url

while(-not $order.CertificateUrl) {
Start-Sleep -Seconds 15;
$order | Update-Order -State $acmeStateDir -PassThru;
}
Write-Host "Exporting certificate - $($certExportPath)";
#Ensure the certificate folder exists
if(-not (Test-Path $certExportDirectory)) {
New-Item -Path $certExportDirectory -ItemType Directory;
}

#remove any existing exported certificate
if(Test-Path $certExportPath) {
Remove-Item -Path $certExportPath -Force
}

As soon as the url shows up we can create the PFX

Export-ACMECertificate -State $acmeStateDir -Order $order -Path $certExportPath;

###############################################################################################
##IIS binding
###############################################################################################
Write-Host "IIS binding";

#Import Certificate
$certStorePath = "Cert:\LocalMachine\My";
$certStore = "My";
$pfx = Import-PfxCertificate -FilePath $certExportPath -CertStoreLocation $certStorePath;
$certThumbprint = $pfx.Thumbprint;

#Create Binding
if(!(Get-WebBinding -Name $iissitename -Port 443 -Protocol "https")){
New-WebBinding -Name $iissitename -IPAddress "*" -Port 443 -Protocol "https" -HostHeader $domain -SslFlags 1 -ErrorAction Stop;
}

#Set Certificate
$binding = Get-WebBinding -Name $iissitename -Port 443 -Protocol "https";
if($binding){
#Check for and remove any existing certificate
if(!($binding.certificateHash -eq "")){
$binding.RemoveSslCertificate();
}
#add the new certificate
$binding.AddSslCertificate($certThumbprint, $certStore);
} else{
throw "Error: SSL certificate assigment to $($iissitename) failed. This can be applied manually instead.";
}`

**Comment by jcnewman83** [comment]
I have updated the question to include the version number as requested, thank you for your response.

**Comment by glatzert** [comment]
1.2.3 was just uploaded. I'm sorry for the inconvenience - I had "remerged" an error from 1.2.0 back to 1.2.2.

I'll setup some tests at last to make this not happen again.

**Comment by jcnewman83** [comment]
Thank you @glatzert I appreciate your help on this. Have a great day!
